### PR TITLE
fix server pending bug + clean up

### LINKED ISSUE #82: /servers filters can get stuck in a pending state
repro:
1. https://joinmastodon.vercel.app/servers
2. use the sitewide dropdown switch to another language

Screen Shot 2022-08-10 at 20 09 27

### PR DESCRIPTION
**Pull request by mikabusante**
closes #82, I was previously pulling the initial query data from the query cache, but it seems this is not shared between locales. Also trying to clean up the code a bit by moving any data transformations into the select option ([reference](https://tkdodo.eu/blog/react-query-data-transformations#3-using-the-select-option))

### CODE REVIEW

**Comment by mikabusante** [comment]
also very extremely excited to learn that react-query has a `keepPreviousData` option, which shows the last data in place of a loading state.....was trying to figure this out with `useRef` as we had before but rlly nice that this is built in https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-3#usepaginatedquery-has-been-deprecated-in-favor-of-the-keeppreviousdata-option

**Review by danielgamage — APPROVED** [review]

**Comment by mikabusante** [comment]
oo is this on preview rn? thought i fixed this in [8fe3e90](https://github.com/oakstudios/joinmastodon/pull/83/commits/8fe3e9020a11965d296430197c26a3e235bcadce) by removing the `apiLanguages.isSuccess` check??

**Comment by danielgamage** [comment]
you know... i thought it was but i can't repro, so maybe i was looking at another branch's preview. sorry for the false alarm!

**Comment by mikabusante** [comment]
no worries, ty for looking! :) gonna merge this!!

**Pull request merged**
